import React, { useState, useEffect, useRef } from 'react';
import { Calculator, ArrowRight, Settings, Info, Copy, Check, RotateCcw, Moon, Sun, BookOpen, ChevronDown, Languages, Circle, Zap, Download, HelpCircle, FileText } from 'lucide-react';
import { calculateTolerance, SUPPORTED_HOLE_LETTERS, SUPPORTED_SHAFT_LETTERS, SUPPORTED_IT_GRADES } from './services/isoService';
import { IsoCalculationResponse, CalculationMode, Language } from './types';
import ToleranceVisualizer from './components/ToleranceVisualizer';
import FitAdvisor from './components/FitAdvisor';
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

interface FitDefinition {
  name: string;
  category: string;
  desc: string;
  type: 'Clearance' | 'Transition' | 'Interference';
}

// UI Translations
const UI_TEXT = {
  en: {
    iso_fit: "ISO Fit Pro",
    local_engine: "Local Engine",
    config: "Configuration",
    tolerance_only: "Tolerance Only",
    fit_calc: "Fit Calculation",
    nominal_size: "Nominal Size",
    supported_range: "Supported range: 0-500mm",
    hole_grade: "Hole Grade",
    shaft_grade: "Shaft Grade",
    calculate: "Calculate",
    calculating: "Calculating...",
    common_fits: "Common Fits Quick Select",
    engineering_rec: "Engineering Recommendation",
    fit_result: "Fit Result",
    fit_characteristics: "Fit Characteristics",
    fit_type: "Fit Type",
    description: "Description",
    source: "Source",
    copy: "Copy Summary",
    copied: "Copied",
    detailed_dim: "Detailed Dimensions",
    component: "Component",
    class: "Class",
    dev_upper: "Deviation (Upper)",
    dev_lower: "Deviation (Lower)",
    max_size: "Max Size",
    min_size: "Min Size",
    hole: "Hole",
    hole_system: "Hole Basis",
    shaft: "Shaft",
    shaft_system: "Shaft Basis",
    enter_params: "Enter parameters to calculate tolerances",
    clearance_fits: "Clearance Fits",
    transition_fits: "Transition Fits",
    interference_fits: "Interference Fits",
    select_system: "Component Type",
    live: "Live",
    export_pdf: "Export PDF",
    developer: "Developed by Eng.Zaher Taleb",
    advisor: "Fit Advisor",
    advisor_desc: "Help me choose",
    pdf_report: "Engineering Report",
    generated_on: "Generated on",
    design_params: "Design Parameters",
    analysis_results: "Analysis Results",
    tolerance_zones: "Tolerance Zones",
    assembly_viz: "Assembly Visualization",
    page: "Page",
    pdf_title: "Engineering Fit Report",
    pdf_subtitle: "ISO 286-1 Standard Analysis",
    tech_desc: "Technical Description",
    calc_values: "Calculated Values",
    gen_by: "Generated by ISO Fit Pro",
    max_clearance_label: "Max Clearance",
    min_clearance_label: "Min Clearance",
    max_interference_label: "Max Interference",
    min_interference_label: "Min Interference",
    tooltips: {
        mode: "Choose 'Tolerance Only' for single part limits or 'Fit Calculation' for assembly analysis.",
        nominal: "The basic size (0-500mm) shared by both hole and shaft tolerances.",
        comp_type: "Hole = Internal feature (e.g. cylinder). Shaft = External feature (e.g. pin).",
        hole_grade: "Hole Tolerance: 'Letter' sets position (H=Zero line), 'Number' sets precision (IT grade).",
        shaft_grade: "Shaft Tolerance: 'Letter' sets position (e.g. g=Play), 'Number' sets precision (IT grade)."
    }
  },
  de: {
    iso_fit: "ISO Passung Pro",
    local_engine: "Lokale Engine",
    config: "Konfiguration",
    tolerance_only: "Nur Toleranz",
    fit_calc: "Passungsberechnung",
    nominal_size: "Nennmaß",
    supported_range: "Bereich: 0-500mm",
    hole_grade: "Bohrungstoleranz",
    shaft_grade: "Wellentoleranz",
    calculate: "Berechnen",
    calculating: "Berechne...",
    common_fits: "Häufige Passungen",
    engineering_rec: "Technische Empfehlung",
    fit_result: "Passungsergebnis",
    fit_characteristics: "Passungseigenschaften",
    fit_type: "Passungsart",
    description: "Beschreibung",
    source: "Quelle",
    copy: "Kopieren",
    copied: "Kopiert",
    detailed_dim: "Detaillierte Maße",
    component: "Komponente",
    class: "Klasse",
    dev_upper: "Abmaß (Oben)",
    dev_lower: "Abmaß (Unten)",
    max_size: "Höchstmaß",
    min_size: "Mindestmaß",
    hole: "Bohrung",
    hole_system: "Einheitsbohrung",
    shaft: "Welle",
    shaft_system: "Einheitswelle",
    enter_params: "Parameter eingeben für Berechnung",
    clearance_fits: "Spielpassungen",
    transition_fits: "Übergangspassungen",
    interference_fits: "Übermaßpassungen",
    select_system: "Komponententyp",
    live: "Live",
    export_pdf: "PDF Exportieren",
    developer: "Developed by Eng.Zaher Taleb",
    advisor: "Passungs-Berater",
    advisor_desc: "Hilfe bei Auswahl",
    pdf_report: "Technischer Bericht",
    generated_on: "Erstellt am",
    design_params: "Designparameter",
    analysis_results: "Analyseergebnisse",
    tolerance_zones: "Toleranzfelder",
    assembly_viz: "Montage-Visualisierung",
    page: "Seite",
    pdf_title: "Passungstechnischer Bericht",
    pdf_subtitle: "Analyse nach ISO 286-1",
    tech_desc: "Technische Beschreibung",
    calc_values: "Berechnete Werte",
    gen_by: "Erstellt mit ISO Fit Pro",
    max_clearance_label: "Max. Spiel",
    min_clearance_label: "Min. Spiel",
    max_interference_label: "Max. Übermaß",
    min_interference_label: "Min. Übermaß",
    tooltips: {
        mode: "Wählen Sie 'Nur Toleranz' für Einzelteile oder 'Passungsberechnung' für Baugruppen.",
        nominal: "Das theoretische Grundmaß (0-500mm) für Bohrung und Welle.",
        comp_type: "Bohrung = Innenmaß. Welle = Außenmaß.",
        hole_grade: "Bohrung: 'Buchstabe' = Lage (H=Nulllinie), 'Zahl' = Qualität (IT-Grad).",
        shaft_grade: "Welle: 'Buchstabe' = Lage (z.B. g=Spiel), 'Zahl' = Qualität (IT-Grad)."
    }
  },
  fr: {
    iso_fit: "ISO Fit Pro",
    local_engine: "Moteur Local",
    config: "Configuration",
    tolerance_only: "Tolérance seule",
    fit_calc: "Calcul d'ajustement",
    nominal_size: "Dimension nominale",
    supported_range: "Plage supportée: 0-500mm",
    hole_grade: "Classe Alésage",
    shaft_grade: "Classe Arbre",
    calculate: "Calculer",
    calculating: "Calcul...",
    common_fits: "Sélection rapide d'ajustements",
    engineering_rec: "Recommandation technique",
    fit_result: "Résultat de l'ajustement",
    fit_characteristics: "Caractéristiques",
    fit_type: "Type d'ajustement",
    description: "Description",
    source: "Source",
    copy: "Copier le résumé",
    copied: "Copié",
    detailed_dim: "Dimensions détaillées",
    component: "Composant",
    class: "Classe",
    dev_upper: "Écart supérieur",
    dev_lower: "Écart inférieur",
    max_size: "Dimension Max",
    min_size: "Dimension Min",
    hole: "Alésage",
    hole_system: "Système Alésage Normal",
    shaft: "Arbre",
    shaft_system: "Système Arbre Normal",
    enter_params: "Entrez les paramètres pour calculer",
    clearance_fits: "Ajustements avec jeu",
    transition_fits: "Ajustements incertains",
    interference_fits: "Ajustements avec serrage",
    select_system: "Type de composant",
    live: "Direct",
    export_pdf: "Exporter PDF",
    developer: "Développé par Eng.Zaher Taleb",
    advisor: "Conseiller",
    advisor_desc: "Aidez-moi à choisir",
    pdf_report: "Rapport Technique",
    generated_on: "Généré le",
    design_params: "Paramètres de conception",
    analysis_results: "Résultats d'analyse",
    tolerance_zones: "Zones de tolérance",
    assembly_viz: "Visualisation d'assemblage",
    page: "Page",
    pdf_title: "Rapport d'Ajustement Technique",
    pdf_subtitle: "Analyse Standard ISO 286-1",
    tech_desc: "Description Technique",
    calc_values: "Valeurs Calculées",
    gen_by: "Généré par ISO Fit Pro",
    max_clearance_label: "Jeu Max",
    min_clearance_label: "Jeu Min",
    max_interference_label: "Serrage Max",
    min_interference_label: "Serrage Min",
    tooltips: {
        mode: "Choisissez 'Tolérance seule' pour une pièce ou 'Calcul d'ajustement' pour un assemblage.",
        nominal: "La dimension de base (0-500mm) commune à l'alésage et l'arbre.",
        comp_type: "Alésage = Intérieur. Arbre = Extérieur.",
        hole_grade: "Tolérance Alésage: 'Lettre' = Position (H=Ligne zéro), 'Chiffre' = Qualité (IT).",
        shaft_grade: "Tolérance Arbre: 'Lettre' = Position (ex: g=Jeu), 'Chiffre' = Qualité (IT)."
    }
  },
  ar: {
    iso_fit: "ISO Fit Pro",
    local_engine: "محرك محلي",
    config: "الإعدادات",
    tolerance_only: "تفاوت مفرد",
    fit_calc: "حساب التوافق",
    nominal_size: "المقاس الاسمي",
    supported_range: "النطاق المدعوم: 0-500 مم",
    hole_grade: "درجة الثقب",
    shaft_grade: "درجة العمود",
    calculate: "حساب",
    calculating: "جاري الحساب...",
    common_fits: "توافقات شائعة",
    engineering_rec: "التوصية الهندسية",
    fit_result: "نتيجة التوافق",
    fit_characteristics: "خصائص التوافق",
    fit_type: "نوع التوافق",
    description: "الوصف",
    source: "المصدر",
    copy: "نسخ الملخص",
    copied: "تم النسخ",
    detailed_dim: "أبعاد تفصيلية",
    component: "المكون",
    class: "الفئة",
    dev_upper: "انحراف علوي",
    dev_lower: "انحراف سفلي",
    max_size: "المقاس الأقصى",
    min_size: "المقاس الأدنى",
    hole: "الثقب",
    hole_system: "نظام أساس الثقب",
    shaft: "العمود",
    shaft_system: "نظام أساس العمود",
    enter_params: "أدخل المعلمات لحساب التفاوتات",
    clearance_fits: "توافقات خلوصية",
    transition_fits: "توافقات انتقالية",
    interference_fits: "توافقات تداخلية",
    select_system: "نوع المكون",
    live: "مباشر",
    export_pdf: "تصدير PDF",
    developer: "Developed by Eng.Zaher Taleb",
    advisor: "مستشار التوافقات",
    advisor_desc: "ساعدني في الاختيار",
    pdf_report: "تقرير هندسي",
    generated_on: "تم الإنشاء في",
    design_params: "معلمات التصميم",
    analysis_results: "نتائج التحليل",
    tolerance_zones: "مناطق التفاوت",
    assembly_viz: "تصور التجميع",
    page: "صفحة",
    pdf_title: "تقرير توافقات هندسية",
    pdf_subtitle: "تحليل قياسي وفق ISO 286-1",
    tech_desc: "الوصف الفني",
    calc_values: "القيم المحسوبة",
    gen_by: "تم الإنشاء بواسطة ISO Fit Pro",
    max_clearance_label: "الخلوص الأقصى",
    min_clearance_label: "الخلوص الأدنى",
    max_interference_label: "التداخل الأقصى",
    min_interference_label: "التداخل الأدنى",
    tooltips: {
        mode: "اختر 'تفاوت مفرد' للأجزاء الفردية أو 'حساب التوافق' للتحليل التجميعي.",
        nominal: "المقاس النظري الأساسي (0-500 مم) للثقب والعمود.",
        comp_type: "ثقب = ميزة داخلية. عمود = ميزة خارجية.",
        hole_grade: "تفاوت الثقب: 'الحرف' يحدد الموقع (H=خط الصفر)، 'الرقم' يحدد الدقة.",
        shaft_grade: "تفاوت العمود: 'الحرف' يحدد الموقع (مثلاً g=لعب)، 'الرقم' يحدد الدقة."
    }
  }
};

const getCommonFits = (lang: Language, system: 'hole' | 'shaft'): FitDefinition[] => {
  const isHole = system === 'hole';

  if (lang === 'de') {
      if (isHole) {
        return [
          { name: "H9/d9", category: "Lockere Laufpassung", desc: "Lose Riemenscheiben, landwirtschaftliche Maschinen, Leerlauf-Räder.", type: "Clearance" },
          { name: "H8/e8", category: "Lockere Laufpassung", desc: "Hauptlager in Schwermaschinen, Nockenwellen, Kurbelwellen.", type: "Clearance" },
          { name: "H8/f7", category: "Laufpassung", desc: "Getriebelager, Elektromotoren, Pumpenwellen.", type: "Clearance" },
          { name: "H7/g6", category: "Gleitpassung", desc: "Werkzeugmaschinenspindeln, Kupplungsscheiben, Schieberäder.", type: "Clearance" },
          { name: "H7/h6", category: "Positionierung", desc: "Wechselräder, Riemenscheiben, Kupplungen, Handräder.", type: "Clearance" },
          { name: "H7/k6", category: "Positionierung", desc: "Riemenscheiben mit Passfeder, Zahnräder, Lagerbuchsen.", type: "Transition" },
          { name: "H7/n6", category: "Übergang", desc: "Feste Stopfen, angetriebene Buchsen, Anker auf Wellen.", type: "Transition" },
          { name: "H7/p6", category: "Presspassung", desc: "Standard-Presspassung, Bronzekränze auf Schneckenrädern.", type: "Interference" },
          { name: "H7/s6", category: "Treibpassung", desc: "Dauerhafte Montage, Eisenbahnräder, Stahlnaben.", type: "Interference" },
        ];
      } else {
        // Shaft Basis (h shaft)
        return [
          { name: "D10/h9", category: "Lockere Laufpassung", desc: "Lose Riemenscheiben, landwirtschaftliche Maschinen.", type: "Clearance" },
          { name: "E8/h8", category: "Lockere Laufpassung", desc: "Hauptlager, Schwermaschinen.", type: "Clearance" },
          { name: "F8/h7", category: "Laufpassung", desc: "Getriebelager, Elektromotoren.", type: "Clearance" },
          { name: "G7/h6", category: "Gleitpassung", desc: "Werkzeugmaschinenspindeln, Schieberäder.", type: "Clearance" },
          { name: "H7/h6", category: "Positionierung", desc: "Riemenscheiben, Kupplungen, Handräder.", type: "Clearance" },
          { name: "K7/h6", category: "Positionierung", desc: "Riemenscheiben mit Passfeder, Zahnräder.", type: "Transition" },
          { name: "N7/h6", category: "Übergang", desc: "Feste Stopfen, Anker.", type: "Transition" },
          { name: "P7/h6", category: "Presspassung", desc: "Standard-Presspassung, Naben.", type: "Interference" },
          { name: "S7/h6", category: "Treibpassung", desc: "Dauerhafte Montage, Eisenbahnräder.", type: "Interference" },
        ];
      }
  }
  if (lang === 'fr') {
      if (isHole) {
        return [
          { name: "H9/d9", category: "Jeu large", desc: "Poulies libres, roues folles, machines agricoles.", type: "Clearance" },
          { name: "H8/e8", category: "Jeu large", desc: "Paliers principaux machines lourdes, arbres à cames.", type: "Clearance" },
          { name: "H8/f7", category: "Jeu tournant", desc: "Roulements de boîte, moteurs électriques, pompes.", type: "Clearance" },
          { name: "H7/g6", category: "Jeu glissant", desc: "Broches machines-outils, embrayages, pignons baladeurs.", type: "Clearance" },
          { name: "H7/h6", category: "Positionnement", desc: "Pignons interchangeables, poulies, accouplements.", type: "Clearance" },
          { name: "H7/k6", category: "Positionnement", desc: "Poulies clavetées, engrenages, bagues de roulement.", type: "Transition" },
          { name: "H7/n6", category: "Incertain", desc: "Bouchons fixes, bagues entraînées, induits.", type: "Transition" },
          { name: "H7/p6", category: "Serrage (Presse)", desc: "Serrage standard, couronnes bronze.", type: "Interference" },
          { name: "H7/s6", category: "Serrage fort", desc: "Assemblage permanent, roues ferroviaires.", type: "Interference" },
        ];
      } else {
        // Shaft Basis (h shaft)
        return [
          { name: "D10/h9", category: "Jeu large", desc: "Poulies libres, machines agricoles.", type: "Clearance" },
          { name: "E8/h8", category: "Jeu large", desc: "Paliers principaux, machines lourdes.", type: "Clearance" },
          { name: "F8/h7", category: "Jeu tournant", desc: "Roulements de boîte, moteurs électriques.", type: "Clearance" },
          { name: "G7/h6", category: "Jeu glissant", desc: "Broches machines-outils, pignons baladeurs.", type: "Clearance" },
          { name: "H7/h6", category: "Positionnement", desc: "Poulies, accouplements, volants.", type: "Clearance" },
          { name: "K7/h6", category: "Positionnement", desc: "Poulies clavetées, engrenages.", type: "Transition" },
          { name: "N7/h6", category: "Incertain", desc: "Bouchons fixes, induits.", type: "Transition" },
          { name: "P7/h6", category: "Serrage (Presse)", desc: "Serrage standard, moyeux.", type: "Interference" },
          { name: "S7/h6", category: "Serrage fort", desc: "Assemblage permanent, roues ferroviaires.", type: "Interference" },
        ];
      }
  }
  if (lang === 'ar') {
      if (isHole) {
        return [
          { name: "H9/d9", category: "تشغيلي واسع", desc: "البكرات السائبة، عجلات الخمول، الآلات الزراعية.", type: "Clearance" },
          { name: "H8/e8", category: "تشغيلي واسع", desc: "المحامل الرئيسية في الآلات الثقيلة، أعمدة الكامات.", type: "Clearance" },
          { name: "H8/f7", category: "تشغيلي", desc: "محامل صناديق التروس، المحركات الكهربائية، المضخات.", type: "Clearance" },
          { name: "H7/g6", category: "انزلاقي", desc: "مغازل أدوات التشغيل، أقراص القابض، التروس المنزلقة.", type: "Clearance" },
          { name: "H7/h6", category: "موضعي", desc: "التروس المتغيرة، البكرات، القارنات، العجلات اليدوية.", type: "Clearance" },
          { name: "H7/k6", category: "موضعي", desc: "البكرات ذات المفاتيح، التروس، جلب المحامل.", type: "Transition" },
          { name: "H7/n6", category: "انتقالي", desc: "سدادات ثابتة، جلب مدفوعة، عضو الإنتاج في المحركات.", type: "Transition" },
          { name: "H7/p6", category: "تثبيت بالضغط", desc: "تثبيت بالضغط قياسي، تيجان برونزية على عجلات دودية.", type: "Interference" },
          { name: "H7/s6", category: "دفع", desc: "تجميع دائم، عجلات السكك الحديدية، محاور فولاذية.", type: "Interference" },
        ];
      } else {
        // Shaft Basis (h shaft)
        return [
          { name: "D10/h9", category: "تشغيلي واسع", desc: "البكرات السائبة، الآلات الزراعية.", type: "Clearance" },
          { name: "E8/h8", category: "تشغيلي واسع", desc: "المحامل الرئيسية، الآلات الثقيلة.", type: "Clearance" },
          { name: "F8/h7", category: "تشغيلي", desc: "محامل صناديق التروس، المحركات الكهربائية.", type: "Clearance" },
          { name: "G7/h6", category: "انزلاقي", desc: "مغازل أدوات التشغيل، التروس المنزلقة.", type: "Clearance" },
          { name: "H7/h6", category: "موضعي", desc: "البكرات، القارنات، العجلات اليدوية.", type: "Clearance" },
          { name: "K7/h6", category: "موضعي", desc: "البكرات ذات المفاتيح، التروس.", type: "Transition" },
          { name: "N7/h6", category: "انتقالي", desc: "سدادات ثابتة، عضو الإنتاج.", type: "Transition" },
          { name: "P7/h6", category: "تثبيت بالضغط", desc: "تثبيت بالضغط قياسي، المحاور.", type: "Interference" },
          { name: "S7/h6", category: "دفع", desc: "تجميع دائم، عجلات السكك الحديدية.", type: "Interference" },
        ];
      }
  }
  // Default EN
  if (isHole) {
      return [
        { name: "H9/d9", category: "Loose Running", desc: "Loose pulleys, idle wheels, agricultural machinery parts.", type: "Clearance" },
        { name: "H8/e8", category: "Loose Running", desc: "Main bearings in heavy machinery, camshafts, crankshafts.", type: "Clearance" },
        { name: "H8/f7", category: "Running", desc: "Gearbox bearings, shafts in bushes, electric motors, pumps.", type: "Clearance" },
        { name: "H7/g6", category: "Sliding", desc: "Machine tool spindles, clutch disks, sliding gears.", type: "Clearance" },
        { name: "H7/h6", category: "Locational", desc: "Change gears, pulleys, couplings, spigots, handwheels.", type: "Clearance" },
        { name: "H7/k6", category: "Locational", desc: "Keyed pulleys, gears, bearing bushes, inner bearing races.", type: "Transition" },
        { name: "H7/n6", category: "Transition", desc: "Fixed plugs, driven bushes, armatures on shafts.", type: "Transition" },
        { name: "H7/p6", category: "Press Fit", desc: "Standard press fit, bronze crowns on worm wheels.", type: "Interference" },
        { name: "H7/s6", category: "Drive Fit", desc: "Permanent assembly, railway wheels, steel hubs on steel shafts.", type: "Interference" },
      ];
  } else {
      // Shaft Basis
      return [
        { name: "D10/h9", category: "Loose Running", desc: "Loose pulleys, agricultural machinery, idle wheels.", type: "Clearance" },
        { name: "E8/h8", category: "Loose Running", desc: "Main bearings in heavy machinery, camshafts.", type: "Clearance" },
        { name: "F8/h7", category: "Running", desc: "Gearbox bearings, electric motors, pumps.", type: "Clearance" },
        { name: "G7/h6", category: "Sliding", desc: "Machine tool spindles, sliding gears.", type: "Clearance" },
        { name: "H7/h6", category: "Locational", desc: "Pulleys, couplings, spigots, handwheels.", type: "Clearance" },
        { name: "K7/h6", category: "Locational", desc: "Keyed pulleys, gears, bearing bushes.", type: "Transition" },
        { name: "N7/h6", category: "Transition", desc: "Fixed plugs, armatures on shafts.", type: "Transition" },
        { name: "P7/h6", category: "Press Fit", desc: "Standard press fit, hubs.", type: "Interference" },
        { name: "S7/h6", category: "Drive Fit", desc: "Permanent assembly, railway wheels.", type: "Interference" },
      ];
  }
};

const TooltipLabel: React.FC<{ label: string, text: string, color?: string }> = ({ label, text, color }) => {
  const [show, setShow] = useState(false);
  return (
    <div className="flex items-center gap-2 mb-1.5 relative w-fit">
      <label className={`block text-sm font-medium cursor-help ${color || 'text-slate-600 dark:text-slate-400'}`}
             onMouseEnter={() => setShow(true)}
             onMouseLeave={() => setShow(false)}
             onClick={(e) => { e.preventDefault(); setShow(!show); }}
      >
        {label}
      </label>
      <button 
        type="button"
        className="text-slate-400 hover:text-blue-500 cursor-help transition-colors outline-none focus:text-blue-500"
        onMouseEnter={() => setShow(true)}
        onMouseLeave={() => setShow(false)}
        onClick={() => setShow(!show)}
      >
        <HelpCircle className="w-3.5 h-3.5" />
      </button>
      {show && (
        <div className="absolute bottom-full left-0 mb-2 w-56 p-2.5 bg-slate-800 dark:bg-slate-700 text-white text-xs rounded-lg shadow-xl z-50 animate-in fade-in slide-in-from-bottom-1 duration-200 pointer-events-none">
           <p className="leading-relaxed">{text}</p>
           <div className="absolute left-4 top-full -translate-x-1/2 border-4 border-transparent border-t-slate-800 dark:border-t-slate-700"></div>
        </div>
      )}
    </div>
  );
};

const App: React.FC = () => {
  const [nominalSize, setNominalSize] = useState<number | ''>(40);
  const [mode, setMode] = useState<CalculationMode>(CalculationMode.FIT);
  const [language, setLanguage] = useState<Language>('en');
  
  // Single Mode Type Selection
  const [singleType, setSingleType] = useState<'hole' | 'shaft'>('hole');
  
  // Common Fits System Selection
  const [fitSystem, setFitSystem] = useState<'hole' | 'shaft'>('hole');

  // Split state for dropdowns
  const [holeLetter, setHoleLetter] = useState('H');
  const [holeIT, setHoleIT] = useState('7');
  const [shaftLetter, setShaftLetter] = useState('g');
  const [shaftIT, setShaftIT] = useState('6');

  const [theme, setTheme] = useState<'dark' | 'light'>('light');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<IsoCalculationResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [advisorOpen, setAdvisorOpen] = useState(false);
  
  const t = UI_TEXT[language];

  useEffect(() => {
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const getHoleGrade = () => `${holeLetter}${holeIT}`;
  const getShaftGrade = () => `${shaftLetter}${shaftIT}`;

  // Live Calculation Effect
  useEffect(() => {
    const calculateResults = async () => {
        if (!nominalSize) {
            setResult(null);
            setError(null);
            return;
        }

        setLoading(true);
        setError(null);

        let grade1: string;
        let grade2: string | undefined;

        if (mode === CalculationMode.FIT) {
            grade1 = `${holeLetter}${holeIT}`;
            grade2 = `${shaftLetter}${shaftIT}`;
        } else {
            // Single mode
            grade1 = singleType === 'hole' ? `${holeLetter}${holeIT}` : `${shaftLetter}${shaftIT}`;
            grade2 = undefined;
        }

        try {
            const data = await calculateTolerance(
                Number(nominalSize),
                mode,
                grade1,
                grade2,
                language
            );
            setResult(data);
        } catch (err) {
            setError(err instanceof Error ? err.message : "An unexpected error occurred");
            // If error (e.g. range), clear valid result
            setResult(null);
        } finally {
            setLoading(false);
        }
    };

    calculateResults();
  }, [nominalSize, mode, singleType, holeLetter, holeIT, shaftLetter, shaftIT, language]);

  const applyCommonFit = (fitName: string) => {
    const [h, s] = fitName.split('/');
    
    // Parse Hole
    const hMatch = h.match(/^([a-zA-Z]+)(\d+)$/);
    if (hMatch) {
      setHoleLetter(hMatch[1]);
      setHoleIT(hMatch[2]);
    }

    // Parse Shaft
    const sMatch = s.match(/^([a-zA-Z]+)(\d+)$/);
    if (sMatch) {
      setShaftLetter(sMatch[1]);
      setShaftIT(sMatch[2]);
    }

    setMode(CalculationMode.FIT);
  };

  const copyToClipboard = () => {
    if (result) {
      navigator.clipboard.writeText(result.text_summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleExportPDF = async () => {
    if (!result) return;
    setIsExporting(true);

    try {
        const reportPage = document.getElementById('pdf-report');
        
        // eslint-disable-next-line new-cap
        const doc = new jsPDF('p', 'mm', 'a4');
        
        if (reportPage) {
             const canvas = await html2canvas(reportPage, { scale: 2 });
             const imgData = canvas.toDataURL('image/png');
             doc.addImage(imgData, 'PNG', 0, 0, 210, 297);
        }

        doc.save(`iso_fit_${result.nominal_size}mm.pdf`);

    } catch (err) {
        console.error("PDF Export failed", err);
    } finally {
        setIsExporting(false);
    }
  };

  const fitsList = getCommonFits(language, fitSystem);
  const groupedFits = fitsList.reduce((acc, fit) => {
    if (!acc[fit.type]) acc[fit.type] = [];
    acc[fit.type].push(fit);
    return acc;
  }, {} as Record<string, FitDefinition[]>);

  const getTypeLabel = (type: string) => {
      if (type === 'Clearance') return t.clearance_fits;
      if (type === 'Interference') return t.interference_fits;
      return t.transition_fits;
  }

  return (
    <div dir={language === 'ar' ? 'rtl' : 'ltr'} className="min-h-screen flex flex-col transition-colors duration-200 bg-slate-100 dark:bg-slate-950 dark:bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] dark:from-slate-900 dark:via-slate-950 dark:to-black text-slate-900 dark:text-slate-200 font-sans selection:bg-blue-500/30">
      
      <FitAdvisor 
        isOpen={advisorOpen} 
        onClose={() => setAdvisorOpen(false)} 
        onSelectFit={applyCommonFit}
        language={language}
      />

      {/* --- HIDDEN PDF REPORT TEMPLATE --- */}
      {/* This renders the PDF pages off-screen. html2canvas will snapshot these. */}
      {result && (
        <div style={{ position: 'fixed', top: 0, left: '-10000px', zIndex: -50 }}>
            <div id="pdf-report" className="w-[794px] min-h-[1123px] bg-white text-slate-900 font-sans relative flex flex-col" dir={language === 'ar' ? 'rtl' : 'ltr'}>
                
                {/* REPORT HEADER */}
                <div className="px-10 py-8 border-b-2 border-slate-800 flex justify-between items-end bg-slate-50">
                    <div>
                        <h1 className="text-3xl font-bold text-slate-900">{t.pdf_title}</h1>
                        <p className="text-sm text-slate-500 mt-1">{t.pdf_subtitle}</p>
                    </div>
                    <div className="ltr:text-right rtl:text-left">
                        <div className="text-2xl font-mono font-bold text-blue-600">
                            {result.nominal_size} mm <span className="text-slate-400">|</span> {result.hole?.grade || '-'}/{result.shaft?.grade || '-'}
                        </div>
                        <div className="text-xs text-slate-400 mt-1 font-mono">
                            {new Date().toLocaleDateString(language, { year: 'numeric', month: 'long', day: 'numeric' })}
                        </div>
                    </div>
                </div>

                {/* CONTENT BODY */}
                <div className="p-10 space-y-8 flex-1">

                    {/* 1. EXECUTIVE SUMMARY & FIT TYPE */}
                    <div className="grid grid-cols-3 gap-6">
                        <div className="col-span-2 bg-slate-50 border border-slate-200 p-5 rounded-lg">
                            <h3 className="text-xs font-bold text-slate-500 mb-3">{t.engineering_rec}</h3>
                            <p className="text-sm leading-relaxed font-medium text-slate-800">
                                {result.recommendation}
                            </p>
                        </div>
                        <div className={`border p-5 rounded-lg flex flex-col justify-center items-center text-center ${
                            result.fit?.type === 'Interference' ? 'bg-red-50 border-red-200 text-red-700' :
                            result.fit?.type === 'Transition' ? 'bg-yellow-50 border-yellow-200 text-yellow-700' :
                            'bg-green-50 border-green-200 text-green-700'
                        }`}>
                            <div className="text-xs font-bold opacity-70 mb-1">{t.fit_type}</div>
                            <div className="text-xl font-bold mb-1">
                                {result.fit ? (
                                    result.fit.type === 'Clearance' ? t.clearance_fits : 
                                    result.fit.type === 'Transition' ? t.transition_fits : t.interference_fits
                                ) : (
                                    'N/A'
                                )}
                            </div>
                        </div>
                    </div>

                    {/* 2. VISUAL ANALYSIS */}
                    <div>
                        <div className="flex items-center gap-2 mb-3 border-b border-slate-100 pb-2">
                            <div className="w-2 h-2 bg-blue-600 rounded-full"></div>
                            <h3 className="text-sm font-bold text-slate-800">{t.analysis_results}</h3>
                        </div>
                        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden p-1 shadow-sm">
                            <ToleranceVisualizer data={result} hideControls language={language} />
                        </div>
                    </div>

                    {/* 3. DIMENSIONAL DATA TABLE */}
                    <div>
                        <div className="flex items-center gap-2 mb-3 border-b border-slate-100 pb-2">
                            <div className="w-2 h-2 bg-blue-600 rounded-full"></div>
                            <h3 className="text-sm font-bold text-slate-800">{t.detailed_dim}</h3>
                        </div>
                        
                        <table className="w-full text-sm border-collapse">
                            <thead>
                                <tr className="bg-slate-100 text-slate-600 text-xs text-left">
                                    <th className="p-3 font-bold border-b border-slate-200 ltr:text-left rtl:text-right">{t.component}</th>
                                    <th className="p-3 font-bold border-b border-slate-200 ltr:text-right rtl:text-left">{t.class}</th>
                                    <th className="p-3 font-bold border-b border-slate-200 ltr:text-right rtl:text-left">{t.dev_upper}</th>
                                    <th className="p-3 font-bold border-b border-slate-200 ltr:text-right rtl:text-left">{t.dev_lower}</th>
                                    <th className="p-3 font-bold border-b border-slate-200 ltr:text-right rtl:text-left bg-slate-200/50">{t.max_size}</th>
                                    <th className="p-3 font-bold border-b border-slate-200 ltr:text-right rtl:text-left bg-slate-200/50">{t.min_size}</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-200 text-slate-700">
                                {result.hole && (
                                <tr>
                                    <td className="p-3 font-bold text-blue-700 ltr:text-left rtl:text-right">{t.hole}</td>
                                    <td className="p-3 font-mono ltr:text-right rtl:text-left">{result.hole.grade}</td>
                                    <td className="p-3 font-mono ltr:text-right rtl:text-left">+{result.hole.es} µm</td>
                                    <td className="p-3 font-mono ltr:text-right rtl:text-left">+{result.hole.ei} µm</td>
                                    <td className="p-3 font-mono font-bold bg-slate-50 ltr:text-right rtl:text-left">{result.hole.max_size.toFixed(3)} mm</td>
                                    <td className="p-3 font-mono font-bold bg-slate-50 ltr:text-right rtl:text-left">{result.hole.min_size.toFixed(3)} mm</td>
                                </tr>
                                )}
                                {result.shaft && (
                                <tr>
                                    <td className="p-3 font-bold text-orange-700 ltr:text-left rtl:text-right">{t.shaft}</td>
                                    <td className="p-3 font-mono ltr:text-right rtl:text-left">{result.shaft.grade}</td>
                                    <td className="p-3 font-mono ltr:text-right rtl:text-left">{result.shaft.es > 0 ? '+' : ''}{result.shaft.es} µm</td>
                                    <td className="p-3 font-mono ltr:text-right rtl:text-left">{result.shaft.ei > 0 ? '+' : ''}{result.shaft.ei} µm</td>
                                    <td className="p-3 font-mono font-bold bg-slate-50 ltr:text-right rtl:text-left">{result.shaft.max_size.toFixed(3)} mm</td>
                                    <td className="p-3 font-mono font-bold bg-slate-50 ltr:text-right rtl:text-left">{result.shaft.min_size.toFixed(3)} mm</td>
                                </tr>
                                )}
                            </tbody>
                        </table>
                    </div>

                    {/* 4. FIT CALCULATION DETAILS */}
                    {result.fit && (
                    <div className="grid grid-cols-2 gap-8 mt-4 pt-4 border-t border-slate-200">
                        <div>
                            <h4 className="text-xs font-bold text-slate-500 mb-2">{t.tech_desc}</h4>
                            <p className="text-sm text-slate-700">{result.fit.description}</p>
                        </div>
                        <div className="ltr:text-right rtl:text-left">
                            <h4 className="text-xs font-bold text-slate-500 mb-2">{t.calc_values}</h4>
                            <div className="space-y-1 text-sm font-mono text-slate-700">
                                {result.fit.max_clearance !== undefined && <div>{t.max_clearance_label}: {result.fit.max_clearance} µm</div>}
                                {result.fit.min_clearance !== undefined && <div>{t.min_clearance_label}: {result.fit.min_clearance} µm</div>}
                                {result.fit.max_interference !== undefined && <div>{t.max_interference_label}: {result.fit.max_interference} µm</div>}
                                {result.fit.min_interference !== undefined && <div>{t.min_interference_label}: {result.fit.min_interference} µm</div>}
                            </div>
                        </div>
                    </div>
                    )}

                </div>

                {/* FOOTER */}
                <div className="px-10 py-6 border-t border-slate-200 bg-slate-50 mt-auto flex justify-between items-center text-xs text-slate-400">
                    <div>
                        {t.gen_by} • {t.developer}
                    </div>
                    <div>
                        {t.page} 1 / 1
                    </div>
                </div>
            </div>
        </div>
      )}

      {/* Header */}
      <header className="border-b border-slate-200 dark:border-slate-800 bg-white/50 dark:bg-slate-900/50 backdrop-blur-md sticky top-0 z-10 transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-blue-600 p-2 rounded-lg shadow-md">
              <Settings className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-slate-800 dark:text-white">
                {language === 'ar' ? 'حاسبة ' : 'ISO'}
                <span className="text-blue-600 dark:text-blue-500">Fit</span>
                {language === 'ar' ? '' : ' Pro'}
            </h1>
          </div>
          <div className="flex items-center gap-3">
             {/* Language Dropdown */}
             <div className="relative group">
                <button className="flex items-center gap-1 p-2 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400 transition-colors text-sm font-medium uppercase">
                    <Languages className="w-4 h-4" />
                    {language}
                </button>
                <div className="absolute ltr:right-0 rtl:left-0 top-full mt-2 w-32 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50">
                    <button onClick={() => setLanguage('en')} className="w-full text-left px-4 py-2 text-sm hover:bg-slate-50 dark:hover:bg-slate-800 rounded-t-lg">English</button>
                    <button onClick={() => setLanguage('de')} className="w-full text-left px-4 py-2 text-sm hover:bg-slate-50 dark:hover:bg-slate-800">Deutsch</button>
                    <button onClick={() => setLanguage('fr')} className="w-full text-left px-4 py-2 text-sm hover:bg-slate-50 dark:hover:bg-slate-800">Français</button>
                    <button onClick={() => setLanguage('ar')} className="w-full text-left px-4 py-2 text-sm hover:bg-slate-50 dark:hover:bg-slate-800 rounded-b-lg font-sans">العربية</button>
                </div>
             </div>

             <button 
               onClick={toggleTheme}
               className="p-2 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400 transition-colors"
             >
                {theme === 'dark' ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
             </button>
          </div>
        </div>
      </header>

      <main className="flex-grow max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Input Section */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-xl transition-colors duration-200">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-lg font-semibold text-slate-800 dark:text-white flex items-center gap-2">
                    <Calculator className="w-5 h-5 text-blue-500" />
                    {t.config}
                </h2>
                <div className="flex items-center gap-2">
                    <button 
                        onClick={() => setAdvisorOpen(true)}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs font-bold uppercase tracking-wider hover:bg-blue-200 dark:hover:bg-blue-900/50 transition-colors"
                    >
                        <HelpCircle className="w-3.5 h-3.5" />
                        {t.advisor}
                    </button>
                    <div className="flex items-center gap-1.5 px-2 py-1 rounded-full bg-green-500/10 border border-green-500/20 text-green-600 dark:text-green-400 text-[10px] font-bold uppercase tracking-wider">
                        <Zap className="w-3 h-3 fill-current" />
                        {t.live}
                    </div>
                </div>
              </div>
              
              <form onSubmit={(e) => e.preventDefault()} className="space-y-6">
                
                {/* Mode Selector */}
                <div>
                  <TooltipLabel label="" text={t.tooltips.mode} />
                  <div className="bg-slate-100 dark:bg-slate-950/50 p-1 rounded-lg flex border border-slate-200 dark:border-slate-800">
                    <button
                        type="button"
                        onClick={() => setMode(CalculationMode.SINGLE)}
                        className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${
                        mode === CalculationMode.SINGLE 
                            ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-white shadow-sm border border-slate-200 dark:border-transparent' 
                            : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
                        }`}
                    >
                        {t.tolerance_only}
                    </button>
                    <button
                        type="button"
                        onClick={() => setMode(CalculationMode.FIT)}
                        className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${
                        mode === CalculationMode.FIT 
                            ? 'bg-blue-50 dark:bg-blue-600/20 text-blue-700 dark:text-blue-400 border border-blue-200 dark:border-blue-600/30 shadow-sm' 
                            : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
                        }`}
                    >
                        {t.fit_calc}
                    </button>
                  </div>
                </div>

                {/* Nominal Size */}
                <div>
                  <TooltipLabel label={t.nominal_size} text={t.tooltips.nominal} />
                  <div className="relative">
                    <input
                      type="number"
                      value={nominalSize}
                      onChange={(e) => setNominalSize(e.target.value === '' ? '' : Number(e.target.value))}
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg px-4 py-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all outline-none font-mono text-lg ltr:text-left rtl:text-right"
                      placeholder="e.g. 40"
                      min="0"
                      max="500"
                      step="0.01"
                      required
                    />
                    <span className="absolute right-4 top-3.5 text-slate-400 dark:text-slate-500 font-mono rtl:right-auto rtl:left-4">mm</span>
                  </div>
                  {error && <p className="text-xs text-red-500 mt-2">{error}</p>}
                  {!error && <p className="text-xs text-slate-500 dark:text-slate-600 mt-1">{t.supported_range}</p>}
                </div>

                {/* Single Mode Component Selector */}
                {mode === CalculationMode.SINGLE && (
                   <div className="flex flex-col gap-2">
                        <TooltipLabel label={t.select_system} text={t.tooltips.comp_type} />
                        <div className="flex gap-4">
                            <label className="flex items-center gap-2 cursor-pointer">
                                <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${singleType === 'hole' ? 'border-blue-500' : 'border-slate-400'}`}>
                                    {singleType === 'hole' && <div className="w-2 h-2 rounded-full bg-blue-500" />}
                                </div>
                                <input type="radio" name="compType" value="hole" checked={singleType === 'hole'} onChange={() => setSingleType('hole')} className="hidden" />
                                <span className={`text-sm ${singleType === 'hole' ? 'text-blue-600 dark:text-blue-400 font-medium' : 'text-slate-500'}`}>{t.hole}</span>
                            </label>
                            <label className="flex items-center gap-2 cursor-pointer">
                                <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${singleType === 'shaft' ? 'border-orange-500' : 'border-slate-400'}`}>
                                    {singleType === 'shaft' && <div className="w-2 h-2 rounded-full bg-orange-500" />}
                                </div>
                                <input type="radio" name="compType" value="shaft" checked={singleType === 'shaft'} onChange={() => setSingleType('shaft')} className="hidden" />
                                <span className={`text-sm ${singleType === 'shaft' ? 'text-orange-600 dark:text-orange-400 font-medium' : 'text-slate-500'}`}>{t.shaft}</span>
                            </label>
                        </div>
                   </div>
                )}

                <div className="grid grid-cols-2 gap-4">
                  {/* Hole Grade Dropdowns */}
                  <div className={`transition-all duration-300 ${mode === CalculationMode.FIT || singleType === 'hole' ? 'opacity-100' : 'opacity-30 pointer-events-none grayscale'}`}>
                    <TooltipLabel label={t.hole_grade} text={t.tooltips.hole_grade} color="text-blue-600 dark:text-blue-400" />
                    <div className="flex gap-1">
                      <div className="relative w-2/3">
                        <select
                          value={holeLetter}
                          onChange={(e) => setHoleLetter(e.target.value)}
                          className="w-full appearance-none bg-slate-50 dark:bg-slate-950 border border-blue-200 dark:border-blue-900/30 rounded-lg pl-3 pr-8 py-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all outline-none font-mono text-lg uppercase cursor-pointer"
                        >
                          {SUPPORTED_HOLE_LETTERS.map(l => <option key={l} value={l}>{l}</option>)}
                        </select>
                        <ChevronDown className="absolute right-2 top-4 w-4 h-4 text-blue-400 pointer-events-none rtl:right-auto rtl:left-2" />
                      </div>
                      <div className="relative w-1/3">
                        <select
                          value={holeIT}
                          onChange={(e) => setHoleIT(e.target.value)}
                          className="w-full appearance-none bg-slate-50 dark:bg-slate-950 border border-blue-200 dark:border-blue-900/30 rounded-lg pl-3 pr-6 py-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all outline-none font-mono text-lg cursor-pointer"
                        >
                          {SUPPORTED_IT_GRADES.map(g => <option key={g} value={g}>{g}</option>)}
                        </select>
                      </div>
                    </div>
                  </div>

                  {/* Shaft Grade Dropdowns */}
                  <div className={`transition-all duration-300 ${mode === CalculationMode.FIT || singleType === 'shaft' ? 'opacity-100' : 'opacity-30 pointer-events-none grayscale'}`}>
                    <TooltipLabel label={t.shaft_grade} text={t.tooltips.shaft_grade} color="text-orange-600 dark:text-orange-400" />
                    <div className="flex gap-1">
                      <div className="relative w-2/3">
                        <select
                          value={shaftLetter}
                          onChange={(e) => setShaftLetter(e.target.value)}
                          className="w-full appearance-none bg-slate-50 dark:bg-slate-950 border border-orange-200 dark:border-orange-900/30 rounded-lg pl-3 pr-8 py-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all outline-none font-mono text-lg lowercase cursor-pointer"
                        >
                          {SUPPORTED_SHAFT_LETTERS.map(l => <option key={l} value={l}>{l}</option>)}
                        </select>
                        <ChevronDown className="absolute right-2 top-4 w-4 h-4 text-orange-400 pointer-events-none rtl:right-auto rtl:left-2" />
                      </div>
                      <div className="relative w-1/3">
                        <select
                          value={shaftIT}
                          onChange={(e) => setShaftIT(e.target.value)}
                          className="w-full appearance-none bg-slate-50 dark:bg-slate-950 border border-orange-200 dark:border-orange-900/30 rounded-lg pl-3 pr-6 py-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all outline-none font-mono text-lg cursor-pointer"
                        >
                          {SUPPORTED_IT_GRADES.map(g => <option key={g} value={g}>{g}</option>)}
                        </select>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Calculate button removed for live update */}
              </form>
            </div>

            {/* Common Fits - Enhanced Readability */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-lg transition-colors duration-200">
                <div className="p-4 bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 flex items-center gap-2">
                        <BookOpen className="w-4 h-4" />
                        {t.common_fits}
                    </h3>
                    <div className="flex bg-slate-200 dark:bg-slate-800 rounded-lg p-0.5">
                       <button onClick={() => setFitSystem('hole')} className={`px-2 py-1 text-xs font-medium rounded-md transition-all ${fitSystem === 'hole' ? 'bg-white dark:bg-slate-700 shadow-sm text-blue-600 dark:text-blue-400' : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'}`}>{t.hole_system}</button>
                       <button onClick={() => setFitSystem('shaft')} className={`px-2 py-1 text-xs font-medium rounded-md transition-all ${fitSystem === 'shaft' ? 'bg-white dark:bg-slate-700 shadow-sm text-orange-600 dark:text-orange-400' : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'}`}>{t.shaft_system}</button>
                    </div>
                </div>
                <div className="p-4 space-y-6 max-h-[500px] overflow-y-auto">
                    {['Clearance', 'Transition', 'Interference'].map((type) => (
                        <div key={type}>
                            <h4 className={`text-xs font-bold uppercase mb-3 flex items-center gap-2 
                                ${type === 'Clearance' ? 'text-green-600 dark:text-green-400' : 
                                  type === 'Transition' ? 'text-yellow-600 dark:text-yellow-400' : 
                                  'text-red-600 dark:text-red-400'}`}>
                                <Circle className="w-2 h-2 fill-current" />
                                {getTypeLabel(type)}
                            </h4>
                            <div className="grid grid-cols-1 gap-2">
                                {groupedFits[type]?.map((fit) => {
                                    const [h, s] = fit.name.split('/');
                                    return (
                                        <button
                                            key={fit.name}
                                            onClick={() => applyCommonFit(fit.name)}
                                            className="group flex flex-col p-3 rounded-lg border border-slate-200 dark:border-slate-800 hover:border-blue-400 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-all text-left"
                                        >
                                            <div className="flex items-center justify-between mb-1">
                                                <div className="flex items-center gap-1 font-mono text-sm font-bold">
                                                    <span className="text-blue-600 dark:text-blue-400">{h}</span>
                                                    <span className="text-slate-400">/</span>
                                                    <span className="text-orange-600 dark:text-orange-400">{s}</span>
                                                </div>
                                                <ArrowRight className="w-3 h-3 text-slate-300 group-hover:text-blue-500 transition-colors opacity-0 group-hover:opacity-100" />
                                            </div>
                                            <div className="text-xs font-medium text-slate-700 dark:text-slate-200 mb-0.5">{fit.category}</div>
                                            <div className="text-[10px] text-slate-500 dark:text-slate-400 leading-tight">{fit.desc}</div>
                                        </button>
                                    );
                                })}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
          </div>

          {/* Results Section */}
          <div className="lg:col-span-8">
             {result ? (
               <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                  
                  {/* Visualizer */}
                  <ToleranceVisualizer data={result} language={language} />

                  {/* Summary Card */}
                  <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-xl transition-colors duration-200">
                     <div className="bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 px-6 py-4 flex items-center justify-between">
                        <h2 className="text-lg font-semibold text-slate-800 dark:text-white flex items-center gap-2">
                           <Info className="w-5 h-5 text-blue-500" />
                           {t.fit_characteristics}
                        </h2>
                        <div className="flex items-center gap-2">
                            <button
                                onClick={handleExportPDF}
                                disabled={isExporting}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-md transition-colors disabled:opacity-50"
                            >
                                <Download className="w-3.5 h-3.5" />
                                {isExporting ? '...' : t.export_pdf}
                            </button>
                            <button
                                onClick={copyToClipboard}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/30 rounded-md transition-colors"
                            >
                                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                                {copied ? t.copied : t.copy}
                            </button>
                        </div>
                     </div>

                     <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-8">
                        {/* Text Details */}
                        <div>
                           {result.fit && (
                              <div className="mb-6">
                                 <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">{t.fit_type}</h3>
                                 <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm font-bold border ${
                                    result.fit.type === 'Interference' ? 'bg-red-50 text-red-700 border-red-200 dark:bg-red-900/20 dark:text-red-300 dark:border-red-900/50' :
                                    result.fit.type === 'Transition' ? 'bg-yellow-50 text-yellow-700 border-yellow-200 dark:bg-yellow-900/20 dark:text-yellow-300 dark:border-yellow-900/50' :
                                    'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/20 dark:text-green-300 dark:border-green-900/50'
                                 }`}>
                                    {result.fit.type === 'Clearance' ? t.clearance_fits : result.fit.type === 'Transition' ? t.transition_fits : t.interference_fits}
                                 </div>
                                 <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{result.fit.description}</p>
                              </div>
                           )}

                           <div>
                              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">{t.engineering_rec}</h3>
                              <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed border-l-2 border-blue-500 pl-3">
                                 {result.recommendation}
                              </p>
                           </div>
                           
                           <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800">
                              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">{t.source}</h3>
                              <p className="text-xs text-slate-400 font-mono">{result.iso_standard}</p>
                           </div>
                        </div>

                        {/* Dimensions Table */}
                        <div>
                           <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">{t.detailed_dim}</h3>
                           <div className="overflow-hidden rounded-lg border border-slate-200 dark:border-slate-800">
                              <table className="w-full text-sm text-left">
                                 <thead className="bg-slate-50 dark:bg-slate-900 text-slate-500 dark:text-slate-400 font-medium border-b border-slate-200 dark:border-slate-800">
                                    <tr>
                                       <th className="px-3 py-2 ltr:text-left rtl:text-right">{t.component}</th>
                                       <th className="px-3 py-2 ltr:text-right rtl:text-left">{t.max_size}</th>
                                       <th className="px-3 py-2 ltr:text-right rtl:text-left">{t.min_size}</th>
                                    </tr>
                                 </thead>
                                 <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                                    {result.hole && (
                                        <tr className="bg-white dark:bg-slate-900/50">
                                            <td className="px-3 py-2 font-medium text-slate-700 dark:text-slate-200 flex items-center gap-2">
                                                <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                                                {t.hole} <span className="text-xs font-mono text-slate-400">({result.hole.grade})</span>
                                            </td>
                                            <td className="px-3 py-2 text-right font-mono text-slate-600 dark:text-slate-300">{result.hole.max_size.toFixed(3)}</td>
                                            <td className="px-3 py-2 text-right font-mono text-slate-600 dark:text-slate-300">{result.hole.min_size.toFixed(3)}</td>
                                        </tr>
                                    )}
                                    {result.shaft && (
                                        <tr className="bg-white dark:bg-slate-900/50">
                                            <td className="px-3 py-2 font-medium text-slate-700 dark:text-slate-200 flex items-center gap-2">
                                                <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                                                {t.shaft} <span className="text-xs font-mono text-slate-400">({result.shaft.grade})</span>
                                            </td>
                                            <td className="px-3 py-2 text-right font-mono text-slate-600 dark:text-slate-300">{result.shaft.max_size.toFixed(3)}</td>
                                            <td className="px-3 py-2 text-right font-mono text-slate-600 dark:text-slate-300">{result.shaft.min_size.toFixed(3)}</td>
                                        </tr>
                                    )}
                                 </tbody>
                              </table>
                           </div>
                           
                           {/* Deviations Compact */}
                           <div className="mt-4 grid grid-cols-2 gap-4">
                              {result.hole && (
                                  <div className="p-3 bg-blue-50 dark:bg-blue-900/10 rounded-lg border border-blue-100 dark:border-blue-900/30">
                                     <div className="text-xs text-blue-600 dark:text-blue-400 font-bold mb-1">{t.hole} {result.hole.grade}</div>
                                     <div className="flex justify-between text-xs text-slate-600 dark:text-slate-400 font-mono">
                                        <span>ES: {result.hole.es > 0 ? '+' : ''}{result.hole.es}</span>
                                        <span>EI: {result.hole.ei > 0 ? '+' : ''}{result.hole.ei}</span>
                                     </div>
                                  </div>
                              )}
                              {result.shaft && (
                                  <div className="p-3 bg-orange-50 dark:bg-orange-900/10 rounded-lg border border-orange-100 dark:border-orange-900/30">
                                     <div className="text-xs text-orange-600 dark:text-orange-400 font-bold mb-1">{t.shaft} {result.shaft.grade}</div>
                                     <div className="flex justify-between text-xs text-slate-600 dark:text-slate-400 font-mono">
                                        <span>es: {result.shaft.es > 0 ? '+' : ''}{result.shaft.es}</span>
                                        <span>ei: {result.shaft.ei > 0 ? '+' : ''}{result.shaft.ei}</span>
                                     </div>
                                  </div>
                              )}
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
             ) : (
                <div className="h-full flex flex-col items-center justify-center text-slate-400 dark:text-slate-600 min-h-[400px] border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-xl bg-slate-50/50 dark:bg-slate-900/50">
                    <Calculator className="w-12 h-12 mb-4 opacity-50" />
                    <p className="text-sm font-medium">{t.enter_params}</p>
                </div>
             )}
          </div>
        </div>
      </main>

      <footer className="mt-auto py-6 border-t border-slate-200 dark:border-slate-800 bg-white/30 dark:bg-slate-900/30 backdrop-blur-sm text-center">
        <p className="text-slate-500 dark:text-slate-400 text-sm font-medium flex items-center justify-center gap-2">
            {t.developer}
        </p>
      </footer>
    </div>
  );
};

export default App;